/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eadapp.ui;

import static eadapp.EadApp.em;
import eadapp.classesEntidade.Conta;
import eadapp.classesEntidade.Curso;
import java.util.Iterator;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author jb_gr
 */
public class VisualizarCursosScreen extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarCursosScreen
     */
    public VisualizarCursosScreen() {
        initComponents();
        /*List<Curso> cursos = em.createQuery("Select c From Curso c",
                                                    Curso.class).getResultList();
        displayCursos(cursos);*/
        Iterator<Curso> iter = cursosQuery.iterator();
        while (iter.hasNext()) {
            Curso c = iter.next();
            
            JButton btnCurso = new javax.swing.JButton();

            btnCurso.setText(c.getNome());
            btnCurso.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCursoActionPerformed(evt, c);
                }
            });

            this.add(btnCurso);
            
            

        }
        this.revalidate();
        this.repaint();
    }
    
    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt, Curso c) {                                         
        CursoScreen mcs;
        System.out.println("eaeee"+c.getLinks());
        
        mcs = new CursoScreen(c);
        mcs.main(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.persistence.Query q = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT c FROM Curso c");
        cursosQuery = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : q.getResultList();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel2.setText("Cursos Inscritos");
        getContentPane().add(jLabel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarCursosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarCursosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarCursosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarCursosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarCursosScreen().setVisible(true);
            }
        });
    }
    
    public void displayCursos(List<Curso> c) {
        cursosQuery.add(c);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List cursosQuery;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
